import '@shared/styles/reset.css';
import '@shared//styles/root.css';
import { Rubik } from 'next/font/google';
import Header from '@app/components/header/header';
import styles from './layout.module.scss';
import cn from 'classnames';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(rubik.className, styles.root)}>
        <Header />
        <div className={styles.root__content}>{children}</div>
      </body>
    </html>
  );
}
